spring:
  cloud:
    stream:
      rocketmq:
        binder:
          namesrv-addr: 127.0.0.1:9876
# 定义name为output的binding
      bindings:
        output1:
          destination: test-topic
          content-type: application/json
# 定义name为input的binding
        input1:
          destination: test-topic
          content-type: application/json
          group: test-group
server:
  port: 1000
